# Generated by Django 6.0.1 on 2026-01-20 12:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gbif_dataset_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=100)),
                ('vernacular_name', models.CharField(blank=True, max_length=100)),
                ('gbif_taxon_key', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbif_id', models.CharField(max_length=100)),
                ('occurrence_id', models.TextField()),
                ('source_dataset_gbif_key', models.CharField(editable=False, max_length=255)),
                ('stable_id', models.GeneratedField(db_persist=True, expression=models.Func(django.db.models.functions.text.Concat('source_dataset_gbif_key', models.Value('|'), 'occurrence_id', output_field=models.TextField()), function='md5', template='(%(function)s(%(expressions)s))::uuid'), output_field=models.UUIDField())),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
                ('date', models.DateField()),
                ('individual_count', models.IntegerField(blank=True, null=True)),
                ('locality', models.TextField(blank=True)),
                ('municipality', models.TextField(blank=True)),
                ('basis_of_record', models.TextField(blank=True)),
                ('recorded_by', models.TextField(blank=True)),
                ('coordinate_uncertainty_in_meters', models.FloatField(blank=True, null=True)),
                ('references', models.TextField(blank=True)),
                ('source_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.dataset')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.species')),
            ],
            options={
                'indexes': [models.Index(fields=['stable_id'], name='alerts_obse_stable__9080e1_idx')],
            },
        ),
    ]
