# Generated by Django 6.0.1 on 2026-01-20 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_frequency', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('auto_mark_seen_after_days', models.PositiveIntegerField(default=365)),
                ('unseen_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('datasets', models.ManyToManyField(blank=True, to='alerts.dataset')),
                ('species', models.ManyToManyField(blank=True, to='alerts.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField()),
                ('observation_date', models.DateField()),
                ('first_seen_in_alert', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alert')),
            ],
            options={
                'indexes': [models.Index(fields=['alert', 'observation_date'], name='alerts_aler_alert_i_1af387_idx'), models.Index(fields=['alert', 'first_seen_in_alert'], name='alerts_aler_alert_i_e11978_idx'), models.Index(fields=['stable_id'], name='alerts_aler_stable__3ba8f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('alert', 'stable_id'), name='unique_alert_observation')],
            },
        ),
    ]
