# Generated by Django 6.0.1 on 2026-01-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_alertobservation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['date'], name='alerts_obse_date_1c82fb_idx'),
        ),
    ]
